require "MINT-core/model/cui/gfx/CIO"
require "MINT-core/model/cui/gfx/CIC"
require "MINT-core/model/cui/gfx/html/HTMLWidget"
require "MINT-core/model/cui/gfx/html/Image"
require "MINT-core/model/cui/gfx/html/Button"
require "MINT-core/model/cui/gfx/html/CarouFredSel"
require "MINT-core/model/cui/gfx/html/VideoPlayer"