source :rubygems
gem "oj"
gem "multi_json"
gem "MINT-statemachine", "~> 1.3.0"
gem "MINT-scxml",  "~> 1.1.0"
gem "MINT-core", :path => '../MINT-core' # "~> 2.0.0"
gem "redis"
gem "rspec", "1.3.1"
gem "eventmachine", "0.12.10"
gem "dm-core"
gem "dm-types"
gem "dm-redis-adapter",  "~> 0.8.0"
gem "dm-serializer"
gem "cassowary","1.0.1"
gem "rmagick","2.12.2"
gem "em-hiredis", :git => "git://github.com/mloughran/em-hiredis.git", :branch => "experimental"
gem "activesupport"
gem "rubysdl","2.1.2"
