source :rubygems
gem "MINT-statemachine", :path => "../statemachine" # "~> 1.2.3"
gem "MINT-scxml", :path => "../scxml" # "~> 1.0.0"
gem "MINT-core", :path => '../MINT-core' # "1.0.0"
#gem "MINT-sdl", :path =>"../MINT-sdl"
gem "redis"
gem "rspec", "1.3.1"
gem "eventmachine", "0.12.10"
gem "dm-core"
gem "dm-types"
gem "dm-redis-adapter" , :path => "../dm-redis-adapter"
gem "dm-serializer"
gem "cassowary","1.0.1"
gem "rmagick","2.12.2"
gem "em-hiredis", :path => "../em-hiredis" #, :git => "git://github.com/rails/rails.git", :tag => "v0.1.1"
gem "activesupport"
gem "rubysdl","2.1.2"
